---
  - name: Default to {{ apt_default_unknown_debian }} when ansible can't read out release name on debian
    set_fact:
      ansible_distribution_release: "{{ apt_default_unknown_debian }}"
    when: ansible_distribution_release == "NA" and ansible_distribution == "Debian"

  - set_fact:
      apt_sources_list: etc_apt_sources.list_debian.j2
    when: ansible_distribution == "Debian"

  - set_fact:
      apt_sources_list: etc_apt_sources.list_ubuntu.j2
    when: ansible_distribution == "Ubuntu"

  - name: install apt sources configuration
    become: True
    template:
      src: "{{ apt_sources_list }}"
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: 0644
    notify: apt update cache
    when: not apt_is_special_snowflake

  - name: install apt sources configuration
    become: True
    template:
      src: etc_apt_sources.list.d_10backports.list.j2
      dest: /etc/apt/sources.list.d/10backports.list
      owner: root
      group: root
      mode: 0644
    notify: apt update cache
    when: apt_with_backports | bool

  - name: Add custom apt repo
    block:
      - name: Add custom repo key
        apt_key:
          data: "{{ apt_custom_repo_key }}"
          state: present
      - name: Add custom repo
        apt_repository:
          repo: "{{ apt_custom_repo_url }}"
          state: present
        notify: apt update cache
    become: True
    when: apt_add_custom_repo | bool

  - meta: flush_handlers

  - name: install programs
    become: True
    apt:
     name:
       - debian-goodies
       - unattended-upgrades
     state: present
     update_cache: yes
     cache_valid_time: 1800

  - name: Enable unattended upgrades
    become: True
    when: apt_unattended_upgrades | bool
    template:
      src: 50unattended-upgrades.j2
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      owner: root
      group: root
      mode: 0644

  - name: delete apt.conf
    become: True
    file:
      path: /etc/apt/apt.conf
      state: absent

  - name: install extra tools
    become: True
    apt:
      name:
        - aptitude
        - apt-file
      state: present
      update_cache: yes
      cache_valid_time: 1800
    when: apt_install_extra | bool

  - name: install aptitude configuration
    become: True
    copy:
      src: etc_apt_apt.conf.d_99aptitude
      dest: /etc/apt/apt.conf.d/99aptitude
      owner: root
      group: root
      mode: 0644
    when: apt_install_extra | bool

  - name: Install host-specific programs
    become: True
    when: host_pkgs != []
    apt:
      name: "{{ host_pkgs }}"
      state: present
